blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
   
]

thanmaya/urls.py
"""from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('blog.urls'))

]"""
from django.contrib import admin
from django.urls import path, include
from blog import views as blog_view
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static


 
urlpatterns = [
 
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', blog_view.Login, name ='login'),
    path('logout/', auth.LogoutView.as_view(template_name ='index.html'), name ='logout'),
    path('register/', blog_view.register, name ='register'),
    path('slideshow/', blog_view.slideshow, name='slideshow'),
     path('home/', blog_view.home, name='home'),
     path('post/', blog_view.post, name='post'),
     path('contact/', blog_view.contact, name='contact'),
     path('postindex/', blog_view.post_index, name='postindex'),
     path("post/<int:pk>/", blog_view.blog_detail, name="blog_detail"),
     path("category/<category>/", blog_view.blog_category, name="blog_category"),
     

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# blog/models.py

from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "categories"

    def _str_(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts")
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
  

    def _str_(self):
        return self.title

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)

    def _str_(self):
        return f"{self.author} on '{self.post}'"

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
 
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length = 20)
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'password1', 'password2']
class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Your Name"}
        ),
    )
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Leave a comment!"}
        )
    )

blog/views.py
"""from django.shortcuts import render

# Create your views here.
def index(request):
     return render(request,'index.html')"""
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.shortcuts import render
from blog.models import Post, Comment
from django.http import HttpResponseRedirect
from blog.forms import CommentForm
  
  
#################### index####################################### 
def index(request):
    return render(request, 'index.html', {'title':'index'})
  
########### register here ##################################### 
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            ######################### mail system #################################### 
            htmly = get_template('Email.html')
            d = { 'username': username }
            subject, from_email, to = 'Email Confirmation', 'your_email@gmail.com', email
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            ################################################################## 
            messages.success(request, f'Your account has been created ! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'Register.html', {'form': form, 'title':'register here'})
  
# login forms#
def Login(request):
    if request.method == 'POST':
  
        # AuthenticationForm_can_also_be_used__
  
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' welcome {username} !!')
            return redirect('slideshow')
        else:
            messages.info(request, f'account done not exit plz sign in')
    form = AuthenticationForm()
    return render(request, 'Login.html', {'form':form, 'title':'log in'})


def slideshow(request):
    # view logic here
    return render(request, 'slideshow.html')
    
def home(request):
    return render(request, 'home.html')
def post(request):
    return render(request, 'post.html')
def contact(request):
    return render(request, 'contact.html')
def aindex(request):
    return render(request, 'aindex.html')

def post_index(request):
    posts = Post.objects.all().order_by("-created_on")
    context = {
        "posts": posts,
    }
    return render(request, "postindex.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by("-created_on")
    context = {
        "category": category,
        "posts": posts,
    }
    return render(request, "category.html", context)

def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post,
            )
            comment.save()
            return HttpResponseRedirect(request.path_info)
   
    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
         "comments": comments,
        "form": CommentForm(),
    }
    

    return render(request, "detail.html", context)
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from .models import Post

@require_POST
def update_like(request):
    post_id = request.POST.get('post_id')
    if post_id:
        post = get_object_or_404(Post, pk=post_id)
        post.likes += 1
        post.save()
        return JsonResponse({'status': 'success', 'likes': post.likes})
    return JsonResponse({'status': 'error', 'message': 'Post ID not provided or invalid'})

thanmaya/templates/Email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Successfully SignedIn</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Dear {{username}}, Thank you for visiting our Blog.</p>
			</section>
		</div>
	</body>
</html>

thanmaya/templates/Login.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
<center>
<form method="POST" style="background-image:url('/static/images/lbg1.jpg');border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
	{% csrf_token %}
	<fieldset class="form-group">
	{{ form|crispy}}
	</fieldset>
<center>
	<button style="background: rgb(249, 171, 192); font-size: 2rem; padding:1%;" id class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in" id="s1" ></span> login</button>
</center>
<br/>
<sub style="text-align: left;"><a href="{% url 'register' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
</form>
</center>
</div>
{% endblock start %}

thanmaya/templates/about.html
<!doctype html>
<!--
	Itsy by FreeHTML5.co
	Twitter: https://twitter.com/fh5co
	Facebook: https://fb.com/fh5co
	URL: https://freehtml5.co
-->
<html class="home blog no-js" lang="en-US">
<head>
    <title>Itsy | A cutesy little template by FreeHTML5.co</title>

    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css" media="all"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC%3A400%2C700%7CLato%3A400%2C700%2C400italic%2C700italic&amp;ver=4.9.8"
          type="text/css" media="screen"/>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="print.css" type="text/css" media="print"/>
    <!--[if (lt IE 9) & (!IEMobile)]>
    <link rel="stylesheet" id="lt-ie9-css" href="ie.css" type="text/css" media="screen"/>
    <![endif]-->
    <script src='js/jquery-3.0.0.min.js'></script>
    <script src='js/jquery-migrate-3.0.1.min.js'></script>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body class="home sticky-menu sidebar-off" id="top">

<header class="header">

    <div class="header-wrap">

        <div class="logo plain logo-left">
            <div class="site-title">
                <a href="index.html" title="Go to Home">Itsy</a>
            </div>
        </div><!-- /logo -->


        <nav id="nav" role="navigation">
            <div class="table">
                <div class="table-cell">
                    <ul id="menu-menu-1" class="">
                        <li class="menu-item">
                            <a href="index.html">Home</a></li>
                        <li class="menu-item current-menu-item">
                            <a href="about.html">About me</a></li>
                        <li class="menu-item">
                            <a href="#">Dropdown</a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="#">Cute</a></li>
                                <li class="menu-item">
                                    <a href="#">Fun</a></li>
                                <li class="menu-item">
                                    <a href="#">Fitness</a>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <a href="blog.html">Blog</a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="single.html">Single</a></li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <a href="typography.html">Typography</a></li>
                        <li class="menu-item">
                            <a href="contact.html">Contact me</a></li>
                        <li class="menu-inline menu-item">
                            <a title="Twitter" href="http://twitter.com/fh5co">
                                <i class="fa fa-twitter"></i><span class="i">Twitter</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Facebook" href="http://www.facebook.com/fh5co">
                                <i class="fa fa-facebook"></i><span class="i">Facebook</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Flickr" href="#"><i class="fa fa-flickr"></i><span class="i">Flickr</span></a>
                        </li>
                        <li class="menu-inline menu-item">
                            <a title="Instagram" href="#">
                                <i class="fa fa-instagram"></i><span class="i">Instagram</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <a href="#nav" class="menu-trigger"><i class="fa fa-bars"></i></a>

        <a href="#topsearch" class="search-trigger"><i class="fa fa-search"></i></a>

    </div>

</header>


<div class="wrap full-wrap">
    <div class="main-wrap">

        <section class="main">
            <article class="post page">

                <div class="inner">
                    <h1>About me</h1>
                    <div class="post-content">
                        <p><img class="size-full alignleft rounded" src="images/about-me.jpg" alt="about-clare" width="300" height="300">
                            Hi, my name is Clare and I’m a serial blogger. I love life and more than anything in the whole wide world, I love taking photographs.</p>
                        <p>Oh and did I mention, I quite like blogging?</p>
                        <p>I’m an aspring photographer and this is my little corner of the world, so take a look around and let me know what you think… I’m on these little social networks too…</p>
                        <p>
                            <a target="_self" class="social twitter black" href="#"> Twitter </a>
                            <a target="_self" class="social facebook black" href="#"> Facebook&nbsp;</a>
                            <a target="_self" class="social instagram black" href="#">&nbsp;instagram&nbsp;</a>
                            <a target="_self" class="social flickr black" href="#"> flickr&nbsp;</a>
                        </p>

                    </div>
                </div>

            </article>
            <div class="border"></div>


        </section>


    </div><!-- /main-wrap -->


</div><!-- /wrap -->


<div class="footer-widgets widget-count-4">

    <div class="wrap">

        <div class="mt-about-you-widget">
            <div class="widget footer">

                <img class="mt-about-avatar" src="images/about-me.jpg" alt="Clare Itsy"/>


                <h4>Clare Itsy</h4>

                <div class="mt-about-bio">
                    <p>Hi, my name is Clare and I&#039;m a serial blogger. I love life and more
                    than anything in the whole wide world, I love taking photographs. Oh and did I mention, I quite like
                    blogging?</p>
                </div>


            </div>
        </div>
        <div class="widget footer"><h4>Recent Posts</h4>
            <ul>
                <li>
                    <a href="#">The Lollipop</a>
                </li>
                <li>
                    <a href="#">Running through Chicago</a>
                </li>
                <li>
                    <a href="#">The Apothecary</a>
                </li>
                <li>
                    <a href="#">The Flowers</a>
                </li>
                <li>
                    <a href="#">The Sunny Day</a>
                </li>
            </ul>
        </div>
        <div class="widget footer"><h4>Categories</h4>
            <ul>
                <li class="cat-item cat-item-6">
                    <a href="#" title="A cute little description would go in here">Blog</a>
                </li>
                <li class="cat-item cat-item-7">
                    <a href="#" title="A cute little description would go in here">Cute</a>
                </li>
                <li class="cat-item cat-item-8">
                    <a href="#">Fitness</a>
                </li>
                <li class="cat-item cat-item-9">
                    <a href="#">Fun</a>
                </li>
            </ul>
        </div>
        <div class="widget footer"><h4>Gallery</h4>
            <div class="textwidget">
                <img src="images/gallery.png" alt="">
            </div>
        </div>
    </div>

</div>


<footer class="footer">
    <div class="footer-wrap">
        <div id="footer-text">&copy; 2018 Itsy.
            Designed by <a href="https://freehtml5.co" target="_blank">FreeHTML5</a>.</div>

        <a href="#top" id="btt">Top <i class="fa fa-chevron-up"></i></a>
    </div>
</footer>

<div id="topsearch">
    <div class="table">
        <div class="table-cell">
            <form role="search" method="get" class="searchform" action="index.html">
                <div>
                    <input type="text" value="" name="s" class="s" placeholder="Type and hit enter"/>
                    <input type="submit" class="searchsubmit" value="Search"/>
                </div>
            </form>
        </div>
    </div>
    <a href="#topsearch" class="search-trigger"><i class="fa fa-times"></i></a>
</div>


<script>var ie9 = false;</script>
<!--[if lte IE 9 ]>
<script> var ie9 = true; </script>
<![endif]-->
<script src="js/global-plugins.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>

thanmaya/templates/aindex.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>My Personal Blog</title>
</head>
<body>
<h1>My Personal Blog</h1>
<a href="{% url "postindex" %}">Home</a>
<hr>
{% block page_title %}{% endblock page_title %}
{% block page_content %}{% endblock page_content %}
</body>
</html>

thanmaya/templates/category.html
<!-- blog/templates/blog/category.html -->

{% extends "blog/aindex.html" %}

{% block page_title %}
<h2>{{ category }}</h2>
{% endblock page_title %}

thanmaya/templates/detail.html
{% block styles %}
    <style>
        body{
            
            align-items: center;
    
        }
        .page-title {
            text-align: center;
            margin-bottom: 20px;
        }

        .meta-info {
            font-size: 14px;
            color: #666666;
            margin-bottom: 15px;
        }

        .meta-info a {
            margin-right: 10px;
            text-decoration: none;
            color: #333333;
            background-color: #f2f2f2;
            padding: 4px 8px;
            border-radius: 4px;
        }

        .meta-info a:hover {
            background-color: #e0e0e0;
        }

        .post-body {
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .comments-section {
            margin-top: 30px;
        }

        .comment {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #fafafa;
            border: 1px solid #e0e0e0;
        }

        .comment-date {
            font-size: 12px;
            color: #666666;
            margin-bottom: 5px;
        }

        .comment-author {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .comment-body {
            line-height: 1.4;
        }

        .comment-form {
            margin-top: 30px;
           
            padding-top: 20px;
        }

        .comment-form label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        .comment-form input[type="text"],
        .comment-form textarea {
            
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }

        .comment-form button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .comment-form button:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock styles %}

{% block page_title %}
    <div class="page-title">
        <h2>{{ post.title }}</h2>
    </div>
{% endblock page_title %}

{% block page_content %}
<center>
    <div class="meta-info">
        <small>
            {{ post.created_on.date }} | Categories:
            {% for category in post.categories.all %}
                <a href="{% url 'blog_category' category.name %}">
                    {{ category.name }}
                </a>
            {% endfor %}
        </small>
    </div>
    <div class="post-body">
        <p>{{ post.body | linebreaks }}</p>
    </div>

    <div class="comments-section">
        <h3>Leave a comment:</h3>
        <form method="post" class="comment-form">
            {% csrf_token %}
            <div>
                <label for="id_body">Comment:</label>
                {{ form.body }}
            </div>
            <!-- Displaying the username of the logged-in user -->
            <div>
                <label for="id_author">Name:</label>
                <input type="text" id="id_author" name="author" value="{{ user.username }}" readonly>
            </div>
            <button type="submit">Submit</button>
        </form>

        <h3>Comments:</h3>
        {% for comment in comments %}
            <div class="comment" style="width: 50%;">
                <div class="comment-date">
                    On {{ comment.created_on.date }} by <span class="comment-author">{{ comment.author }}</span>
                </div>
                <div class="comment-body">
                    {{ comment.body | linebreaks }}
                </div>
            </div>
            {% endfor %}
        </div>
</center>
    </div>
{% endblock page_content %}

thanmaya/templates/home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<html class="home blog no-js" lang="en-US">
<head>
    <title>Maya| A cutesy little blog</title>

    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="{% static 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}"
          type="text/css" media="all"/>
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Amatic+SC%3A400%2C700%7CLato%3A400%2C700%2C400italic%2C700italic&amp;ver=4.9.8' %}"
          type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'print.css' %}" type="text/css" media="print"/>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>

    <style>
        #a1{
            color: rgb(115, 235, 235);
           }
           #h1{
            font-size: 75px;
           }
    </style>
</head>
<body class="home sticky-menu sidebar-off" id="top">
    
<br><br><br>
      </body>
<header class="header">

    <div class="header-wrap">
        <nav id="nav" role="navigation" style="padding-top: 5px;">
            <div class="table">
                <div class="table-cell">
                    <ul id="menu-menu-1">
                        <li class="menu-item">
                            <a href="index.html"></a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url "logout" %}" id="a1"><span class="glyphicon glyphicon-log-in"> Logout </span></a></li>
                            {% else %}
                            <li><a href="{% url "register" %}"></a></li>
                            <li><a href="{% url "login" %}"></a></li>
                            {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <a href="#nav" class="menu-trigger"><i class="fa fa-bars"></i></a>

        <a href="#topsearch" class="search-trigger"><i class="fa fa-search"></i></a>

    </div>

</header>

<div class="hero" style="background-image: url('/static/images/bg1.png'); text-align:right;">
    <div class="hero-inner">
        <div class="inner">
            <h1 id="h1"  style="color: rgb(238, 161, 161); font-family:'Pacifico',cursive;"><span class="border border-top border-bottom">Maya</span></h1>
            <div class="hero-line-one"></div>
            <div class="hero-line-two"><span class="border border-bottom"><p style="color:#f39c9c;font-family: Times New Roman, Times, serif;">It's all about me</p></span></div>
        </div>

    </div>

</div>
<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main main-archive">
            <div class="loop">

                <article class="post format-gallery post_format-post-format-gallery">
                        <div class="part-gallery">
                            <div class="flexslider">
                                <ul class="slides">
                                    <li><span class="post-image"><img src="{% static 'images/run3.jpg' %}"
                                                                      alt="Run-3"/></span></li>
                                </ul>
                            </div>
                        </div>

                    </a>
   
                    <div class="inner">
                        <h2 class="entry-title">
                           <p>My College </p>
                        </h2>
                        <ul class="meta top">
                            <li class="time">
                                    <time class="post-date updated" datetime="2015-02-01">December 13,2021</time>
                                </a></li>
                        </ul>
                        <div class="post-content">
                            <p>Sree Vidyanikethan Education Trust (SVET) was established in 1992, it has surpassed many a milestone. As an individual, I have the best memories and biggest learning experiences in life. I believe every individual deserves best knowledge to 
                                lead a better life and knowledge comes with learning – one that is based on doing things right 
                                and not merely knowing about how to do them.
                                At SVEC, our purpose is to transform young aspirers into exceptional professionals, our mission is to enhance the aptitudes of those who walk in to acquire knowledge and our dream is to give every young child access to best education and progression in life. Today, I am so glad and happy to see SVEC positioned as one of the best colleges for engineering in India..</p>
                    
                        </div>
                        <a
                                        href="https://www.svec.education/"
                                        class="more-link">Read 
                                        More</a>
                        </ul>
                        </div>
            </div>

        </section>
        <center><a href="{% url 'postindex' %}" id="a1"><h4>TO SEE OUR POSTS</h4></a></center>
        <center><a href="{% url "post" %}" id="a1"><h2>Post your thoughts here and spark conversations.</h2></a></center>

<div class="footer-widgets widget-count-4">
    <div class="wrap">
        <div class="mt-about-you-widget">
            <div class="widget footer">
                <img class="mt-about-avatar" src="/static/images/about.jpg" alt="Thanmaya"/>
                <h4>Thanmaya</h4>
                <div class="mt-about-bio">
                    <p>Hi, my name is Thanmaya and I&#039;m a student . I love beaches,travelling and
                                doing arts and crafts</p>
                </div>

            </div>
        </div>
        <div class="widget footer"><h4>Recent Posts</h4>
            <ul>
                <li>
                    <a href="#">Place</a>
                </li>
                <li>
                    <a href="#">Movie</a>
                </li>
                <li>
                    <a href="#">Cricketer</a>
                </li>
                <li>
                    <a href="#">Food</a>
                </li>
                <li>
                    <a href="#">Thing</a>
                </li>
                <li>
                    <a href="#">Book</a>
                </li>
            </ul>
        </div>
        
        <div class="widget footer"><h4>Gallery</h4>
            <div class="textwidget">
                <img src="/static/images/gallery.jpg" alt="">
            </div>
        </div>
    </div>

</div>

<div id="topsearch">
    <div class="table">
        <div class="table-cell">
            <form role="search" method="get" class="searchform" action="index.html">
                <div>
                    <input type="text" value="" name="s" class="s" placeholder="Type and hit enter"/>
                    <input type="submit" class="searchsubmit" value="Search"/>
                </div>
            </form>
        </div>
    </div>
    <a href="#topsearch" class="search-trigger"><i class="fa fa-times"></i></a>
</div>

<script>var ie9 = false;</script>
<!--[if lte IE 9 ]>
<script> var ie9 = true; </script>
<![endif]-->
<script src="{% static 'js/global-plugins.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>
        
       
    

thanmaya/templates/homeold.html
{% extends 'base.html' %}
{% block content %}
<h1>Hello {{name}}!!!!!!!!</h1>

<form action="add" method="post">
    {% csrf_token %}
    Enter 1st number: <input type="text" name="num1"><br>
    Enter 2nd number: <input type="text" name="num2"><br>
    <input type="submit">

</form>
{% endblock %}

thanmaya/templates/loginold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="login" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="Submit">
        <div>
            {% for message in messages %}
         <h3>
            {{message}}
        </h3>
        {% endfor %}
    </div>
    </form>
</body>
</html>

thanmaya/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HELLO</h1>
</body>
</html>

thanmaya/templates/result.html
{% extends 'base.html' %}
{% block content %}
Result: {{result}}
{% endblock %}